spring:
  profiles:
    active: dev

mybatis:
  #mapper.xml存放路径（resource）
  mapper-locations: classpath:mapper/*.xml
  #mapper接口文件存放路径
  type-aliases-package: com.gw.gwdemo.mapper

devtools:
  restart:
    enabled: true #是否支持热部署

#mybaatis分页插件pagehelper设置
pagehelper:
  pagehelperDialect: mysql
  reasonable: true
  support-methods-arguments: true