spring:
  profiles:
    active: dev

mybatis:
  #mapper.xml存放路径（resource）
  mapper-locations: classpath:mapper/*.xml
  #mapper接口文件存放路径
  type-aliases-package: com.gw.gwdemo.mapper

devtools:
  restart:
    enabled: true #是否支持热部署

#mybaatis分页插件pagehelper设置
pagehelper:
  pagehelperDialect: mysql
#  关于reasonable参数:
#  true，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
#  false，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: false
  support-methods-arguments: true
  params: count=countSql