server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_shopmaster?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12345678
    max-idle: 10
    min-idle: 5
    initial-size: 5
    #mysql-connector-java 版本在6.0以上要用 com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-wait: 10000
  jpa:
    database: mysql
